# https://gohugo.io/getting-started/configuration/

baseURL = "https://www.integralist.co.uk/"
languageCode = "en-gb"
title = "integralist"
theme = "minimo"

googleAnalytics = "UA-33159515-1"
paginate = 10

preserveTaxonomyNames = true

[params]
description = "Compassionate Listener. Polyglot. Author. Husband. Father. He/Him."
dateFormat = "2006-01-02"
copyrightOwner = "integralist"
copyrightStartYear = "2017"
# hideEntryNavigation = false
customCSS = ["css/custom.css", "css/highlight.github.css"]
# customJS = ["js/custom.js", "js/highlight.pack.js", "js/highlight-trigger.js"] # DISABLED as the highlight caused colour issues.
customJS = ["js/custom.js", "js/highlight.pack.js"]
# hideSocialMenu = false
showReadTime = true

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "⋆"

[taxonomies]
category = "categories"
tag = "tags"

[author]
name = "Mark McDonnell"

[author.social]
github = "integralist"
instagram = "integralist"
twitter = "integralist"

[permalinks]
page = "/:slug/"

[[menu.main]]
name = "About "
url = "/about"
weight = 200

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 300

[[menu.main]]
name = "Search "
url = "/search"
weight = 400

[[menu.main]]
name = "Resume "
url = "/resume"
weight = 500

[[menu.main]]
name = "Day Mode"
url = "#theme"
weight = 600

# Language Configuration
defaultContentLanguage = "en"

[languages]
[languages.en.params]
lang = "en"
languageName = "English"
weight = 1

[markup.goldmark.renderer]
unsafe = true
